name: Deploy-Systemd

on:
  push:
    branches: [ "systemd" ]

jobs:

  build-and-deploy:


    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build
        run: go build -v -o app

      - name: SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: deploy
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "app"
          target: "/home/deploy"
          debug: true

      - name: Deploy App
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.HOST }}
          username: deploy
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            set -euo pipefail
            sudo systemctl stop cct1-systemd.service
            sudo mkdir -p /opt/app/bin/
            sudo cp /home/deploy/app /opt/app/bin/
            sudo chown appuser:appuser /opt/app/bin/app
            sudo chmod 750 /opt/app/bin/app
            
            sudo systemctl start cct1-systemd.service
